CoreTestApp/Controllers/SystemSettingsController.cs
using Imobiliare.Entities;
using Imobiliare.Repositories.Interfaces;
using Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Imobiliare.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SystemSettingsController : Controller
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(SystemSettingsController));

        private IUnitOfWork unitOfWork;

        public SystemSettingsController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: SystemSettings
        public ActionResult Index()
        {
            var systemSettings = this.unitOfWork.SystemSettingsRepository.SystemSettings;
            return View(systemSettings);
        }

        public ActionResult Editeaza()
        {
            var systemSettings = this.unitOfWork.SystemSettingsRepository.SystemSettings;
            return View(systemSettings);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editeaza(
          [Bind("Id,DefaultPageSizeAdminPageAnunturi,DefaultPageSizeAdminPageUsers,DefaultPageSizeMainPages,AutoApproveAnunturi,CapchaEnabled,UseFakeEmailManager,NotifyAdminByEmailWhenUserContactsAnotherUser,NotifyAdminByEmailWhenUserChangedAnuntByEmail,AutoSendAnuntExpiratEmails,LogsRetrieveNumber"
          )] SystemSettings systemSettings)
        {
            if (ModelState.IsValid)
            {
                this.unitOfWork.SystemSettingsRepository.UpdateSystemSettings(systemSettings);
                this.unitOfWork.Complete();
                TempData["Message"] = "Setari updatate cu succes";
                log.Debug($"SystemSettings updated by {User.Identity.Name}");
                return RedirectToAction("Index");
            }
            return View(systemSettings);
        }
    }
}

CoreTestApp/Views/SystemSettings/Editeaza.cshtml
@model Imobiliare.Entities.SystemSettings

@Html.Partial("_MenuSuperAdmin")

@{
    Layout = "_LayoutB4";
}

<h2>Edit System Settings</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultPageSizeAdminPageAnunturi, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultPageSizeAdminPageAnunturi, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.DefaultPageSizeAdminPageAnunturi, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultPageSizeAdminPageUsers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultPageSizeAdminPageUsers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultPageSizeAdminPageUsers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DefaultPageSizeMainPages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DefaultPageSizeMainPages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DefaultPageSizeMainPages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AutoApproveAnunturi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.AutoApproveAnunturi, new { style = "width: 100%; height: 50px", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AutoApproveAnunturi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CapchaEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.CapchaEnabled, new { style = "width: 100%; height: 50px", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CapchaEnabled, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UseFakeEmailManager, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.UseFakeEmailManager, new { style = "width: 100%; height: 50px", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UseFakeEmailManager, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NotifyAdminByEmailWhenUserContactsAnotherUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.NotifyAdminByEmailWhenUserContactsAnotherUser, new { style = "width: 100%; height: 50px", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NotifyAdminByEmailWhenUserContactsAnotherUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NotifyAdminByEmailWhenUserChangedAnuntByEmail, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.NotifyAdminByEmailWhenUserChangedAnuntByEmail, new {style = "width: 100%; height: 50px", htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.NotifyAdminByEmailWhenUserChangedAnuntByEmail, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AutoSendAnuntExpiratEmails, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.AutoSendAnuntExpiratEmails, new {style = "width: 100%; height: 50px", htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.AutoSendAnuntExpiratEmails, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogsRetrieveNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogsRetrieveNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogsRetrieveNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

CoreTestApp/Views/SystemSettings/Index.cshtml
@model Imobiliare.Entities.SystemSettings

@Html.Partial("_MenuSuperAdmin")

@{
    ViewBag.Title = "Setari sistem";
    Layout = "_LayoutB4";
}

<h2>SystemSettings</h2>

<br /><br />
<p>
    @Html.ActionLink("Editeaza", "Editeaza" , "SystemSettings", null, new {@class = "btn btn-success"})
</p>

<div>
    @Html.DisplayNameFor(model => model.DefaultPageSizeAdminPageAnunturi)
    @Html.DisplayFor(model => model.DefaultPageSizeAdminPageAnunturi)
</div>
<div>
    @Html.DisplayNameFor(model => model.DefaultPageSizeAdminPageUsers)
    @Html.DisplayFor(model => model.DefaultPageSizeAdminPageUsers)
</div>
<div>
    @Html.DisplayNameFor(model => model.DefaultPageSizeMainPages)
    @Html.DisplayFor(model => model.DefaultPageSizeMainPages)
</div>
<div>
    @Html.DisplayNameFor(model => model.AutoApproveAnunturi)
    @Html.DisplayFor(model => model.AutoApproveAnunturi)
</div>
<div>
    @Html.DisplayNameFor(model => model.CapchaEnabled)
    @Html.DisplayFor(model => model.CapchaEnabled)
</div>
<div>
    @Html.DisplayNameFor(model => model.UseFakeEmailManager)
    @Html.DisplayFor(model => model.UseFakeEmailManager)
</div>
<div>
    @Html.DisplayNameFor(model => model.NotifyAdminByEmailWhenUserContactsAnotherUser)
    @Html.DisplayFor(model => model.NotifyAdminByEmailWhenUserContactsAnotherUser)
</div>
<div>
    @Html.DisplayNameFor(model => model.NotifyAdminByEmailWhenUserChangedAnuntByEmail)
    @Html.DisplayFor(model => model.NotifyAdminByEmailWhenUserChangedAnuntByEmail)
</div>
<div>
    @Html.DisplayNameFor(model => model.AutoSendAnuntExpiratEmails)
    @Html.DisplayFor(model => model.AutoSendAnuntExpiratEmails)
</div>
<div>
    @Html.DisplayNameFor(model => model.LogsRetrieveNumber)
    @Html.DisplayFor(model => model.LogsRetrieveNumber)
</div>