CoreTestApp/Models/SuperAdmin/MaintenanceData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Imobiliare.UI.Models.SuperAdmin
{
    public class MaintenanceData
    {
        public int UsedDbInMb { get; set; }

        public int MaxDbSizeInMb { get; set; }

        public int UsedPercentage => (int) ((double) UsedDbInMb / MaxDbSizeInMb * 100);
    }
}

CoreTestApp/Models/SuperAdmin/MassEmailData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Imobiliare.UI.Models
{
  using Imobiliare.Entities;

  public class MassEmailData
  {
    public MassEmailData()
    {
      this.EmailTemplates = new List<EmailTemplate>();
    }
    public List<EmailTemplate> EmailTemplates { get; set; } 
  }
}

CoreTestApp/Models/SuperAdmin/SuperAdminData.cs
using System.Collections.Generic;

namespace Imobiliare.UI.Models
{
    using Entities;

    public class SuperAdminData : ImobilsData
    {
        public SuperAdminData(List<Imobil> imobils, ImobilFilter imobilFilter, int totalNumberOfImobils)
          : base(imobils, imobilFilter, totalNumberOfImobils)
        {
        }

        public List<EmailTemplate> EmailTemplates { get; set; }
    }
}

CoreTestApp/Controllers/SuperAdminController.cs
using Imobiliare.Entities;
using Imobiliare.Repositories.Interfaces;
using Imobiliare.Repositories;
using Imobiliare.ServiceLayer.Interfaces;
using Imobiliare.UI.Models.SuperAdmin;
using Imobiliare.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Net;
using System.Text.RegularExpressions;
using Imobiliare.Managers.ExtensionMethods;
using Logging;
using System.Drawing.Printing;

namespace Imobiliare.UI.Controllers
{
    /// <summary>
    /// Used for site administrators to approve requests, change user details, etc
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class SuperAdminController : Controller
    {
        private DateTimeFormatInfo dateFormat = new DateTimeFormatInfo { ShortDatePattern = "dd'/'MM'/'yyyy" };

        private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly IEmailManagerService emailManagerService;
        private readonly IExternalSiteParserService externalSiteContentParser;

        private static readonly ILog log = LogManager.GetLogger(typeof(SuperAdminController));

        public SuperAdminController(
          IUnitOfWork unitOfWork,
          IEmailManagerService emailManagerService,
          IExternalSiteParserService externalSiteContentParser,
          IWebHostEnvironment hostingEnvironment)
        {
            this.emailManagerService = emailManagerService;
            this.externalSiteContentParser = externalSiteContentParser;
            this.unitOfWork = unitOfWork;
            this.hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public ActionResult Salam()
        {
            return Ok();
        }

        public ActionResult Index(
          int? JudetSelect,
          int? OrasSelect,
          int? CartierSelect,
          TipVanzator? TipVanzatorSelect,
          StareAprobare? StareAprobareSelect,
          int? page,
          bool? OnlyUserAnunturi,
          bool? OnlyAdminAnunturi,
          string LogStartDate,
          string LogEndDate,
          string UserName,
          bool? FiltareDupaDataAdaugareInitiala)
        {
            int judetId = 0;
            if (JudetSelect != null)
            {
                judetId = JudetSelect.Value;
            }

            int orasId = 0;
            if (OrasSelect != null)
            {
                orasId = OrasSelect.Value;
            }

            int cartierId = 0;
            if (CartierSelect != null)
            {
                cartierId = CartierSelect.Value;
            }

            var tipVanzator = TipVanzator.TotiVanzatorii;
            if (TipVanzatorSelect != null)
            {
                tipVanzator = TipVanzatorSelect.Value;
            }

            int selectedPageFinal = 1;
            if (page != null)
            {
                selectedPageFinal = page.Value;
            }

            var stareAprobare = StareAprobare.Toate;
            if (StareAprobareSelect != null)
            {
                stareAprobare = StareAprobareSelect.Value;
            }

            bool onlyUserAnunturi = false;
            if (OnlyUserAnunturi != null)
            {
                onlyUserAnunturi = OnlyUserAnunturi.Value;
            }

            bool onlyAdminAnunturi = false;
            if (OnlyAdminAnunturi != null)
            {
                onlyAdminAnunturi = OnlyAdminAnunturi.Value;
            }

            DateTime logStartDate = DateTime.MinValue;
            if (!string.IsNullOrEmpty(LogStartDate))
            {
                logStartDate = DateTime.ParseExact(LogStartDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            DateTime logEndDate = DateTime.MinValue;
            if (!string.IsNullOrEmpty(LogEndDate))
            {
                logEndDate = DateTime.ParseExact(LogEndDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }

            UserProfile userprofile = null;
            if (!string.IsNullOrEmpty(UserName))
            {
                userprofile = this.unitOfWork.UsersRepository.GetUserProfiles().FirstOrDefault(x => x.UserName.Contains(UserName));
            }

            bool filtareDupaDataAdaugareInitiala = false;
            if (FiltareDupaDataAdaugareInitiala != null)
            {
                filtareDupaDataAdaugareInitiala = FiltareDupaDataAdaugareInitiala.Value;
            }
            var pageSize = this.unitOfWork.SystemSettingsRepository.SystemSettings.DefaultPageSizeAdminPageAnunturi;
            var imobilFilter = new ImobilFilter { PageSize = pageSize, Page = selectedPageFinal };
            imobilFilter.JudetId = judetId;
            imobilFilter.OrasId = orasId;
            imobilFilter.CartierId = cartierId;
            imobilFilter.TipVanzator = tipVanzator;
            imobilFilter.StareAprobare = stareAprobare;
            imobilFilter.OnlyUserAnunturi = onlyUserAnunturi;
            imobilFilter.OnlyAdminAnunturi = onlyAdminAnunturi;
            imobilFilter.PerioadaStart = logStartDate;
            imobilFilter.PerioadaEnd = logEndDate;
            imobilFilter.UserProfile = userprofile;
            imobilFilter.FiltareDupaDataAdaugareInitiala = filtareDupaDataAdaugareInitiala;

            int totalNumberOfImobils;
            var allImobils = this.unitOfWork.AnunturiRepository.GetAllImobil(imobilFilter, out totalNumberOfImobils);

            var displayPageNumber = (int)Math.Ceiling((double)totalNumberOfImobils / pageSize);
            var superAdminData = new SuperAdminData(allImobils, imobilFilter, displayPageNumber);
            superAdminData.TotalNumberOfEntries = totalNumberOfImobils;
            superAdminData.Judets = this.unitOfWork.JudetRepository.Judete();
            superAdminData.Orases = this.unitOfWork.OrasRepository.GetSelectableOrases(imobilFilter.JudetId);
            superAdminData.Cartiers = this.unitOfWork.CartierRepository.GetSelectableCartiers(imobilFilter.OrasId);

            superAdminData.EmailTemplates =
              this.emailManagerService.GetAllEmailTemplates()
                .Where(x => x.EmailTemplateCategory == EmailTemplateCategory.AdminAnuntRelated)
                .ToList();

            return View(superAdminData);
        }

        /// <summary>
        /// selectSingleUserEmail optional for also redirecting through actions in superadmin to specific user
        /// In order to be able to send email notifications from users view
        /// </summary>
        public ActionResult Users(string selectSingleUserEmail, string userName, string page, string tipVanzatorSelect, string tipRoleSelect)
        {
            var selectedPage = 1;
            if (!string.IsNullOrWhiteSpace(page))
            {
                selectedPage = int.Parse(page);
            }

            var tip = TipVanzator.TotiVanzatorii;
            if (tipVanzatorSelect != null)
            {
                tip = tipVanzatorSelect.EnumParse<TipVanzator>();
            }

            var role = Role.Toti;
            if (tipRoleSelect != null)
            {
                role = tipRoleSelect.EnumParse<Role>();
            }

            if (string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(selectSingleUserEmail))
            {
                userName = selectSingleUserEmail;
            }
            if (!string.IsNullOrEmpty(userName))
            {
                var userProfile = this.unitOfWork.UsersRepository.GetUserProfiles().FirstOrDefault(x => x.UserName.Contains(userName.Trim()));
                if (userProfile != null)
                {
                    return View(new UsersData()
                    {
                        UserProfiles = new List<UserProfile>() { userProfile },
                        EmailTemplates = this.emailManagerService.GetAllEmailTemplates()
                        .Where(x => x.EmailTemplateCategory == EmailTemplateCategory.AdminUserRelated)
                        .ToList()
                    });
                }
            }

            var pageSize = this.unitOfWork.SystemSettingsRepository.SystemSettings.DefaultPageSizeAdminPageUsers;
            var totalNumberOfUsers = 0;
            var userProfiles = this.unitOfWork.UsersRepository.GetUserProfiles(tip, role, selectedPage, pageSize, out totalNumberOfUsers);

            var displayPageNumber = (int)Math.Ceiling((double)totalNumberOfUsers / pageSize);

            var usersData = new UsersData
            {
                SelectedTipVanzator = tip,
                SelectedRole = role,
                UserProfiles = userProfiles,
                Page = selectedPage,
                NumberOfPages = displayPageNumber,
                EmailTemplates = this.emailManagerService.GetAllEmailTemplates()
                .Where(x => x.EmailTemplateCategory == EmailTemplateCategory.AdminUserRelated)
                .ToList()
            };

            //foreach(var user in userProfiles)
            //{
            //    if(user.Anunturi.Count == 0)
            //    {
            //        this.unitOfWork.UsersRepository.DeleteUser(user.Id);
            //        log.Debug($"SuperAdmin bulk hack delete empty users {User.Identity.Name} deleted user {user.Email}");
            //    }
            //}
            //this.unitOfWork.Complete();

            return View(usersData);
        }

        public ActionResult UserEditare(string userid)
        {
            UserProfile user = this.unitOfWork.UsersRepository.GetUserProfileById(userid, true);

            //using (var db = new ApplicationDbContext())
            //{
            //    user = db.Users.Single(u => u.Id == userid);
            //}
            return View(user);
        }

        public ActionResult UpdateUserInfo(UserProfile userProfile)
        {
            this.unitOfWork.UsersRepository.UpdateUserProfileByAdmin(userProfile);
            this.unitOfWork.Complete();

CoreTestApp/Views/SuperAdmin/Maintenance.cshtml
@Html.Partial("_MenuSuperAdmin")
@model Imobiliare.UI.Models.SuperAdmin.MaintenanceData

@{
    Layout = "_LayoutB4";
}

<h2>Maintenance</h2>
<div class="row" style="padding: 0 10px; border: 1px solid rgb(183, 183, 183); border-radius: 3px; background-color: #F9F9F9">
    <h3>Db usage - @Model.UsedDbInMb MB of @Model.MaxDbSizeInMb MB => @Model.UsedPercentage% Used</h3>

    @{
        var level = "info";
        if (Model.UsedPercentage > 50 && Model.UsedPercentage < 75)
        {
            level = "warning";
        }
        else if (Model.UsedPercentage >= 75)
        {
            level = "danger";
        }
    }

    <div class="progress">
        <div class="progress-bar progress-bar-@level progress-bar-striped" role="progressbar" aria-valuenow="@Model.UsedPercentage" aria-valuemin="0" aria-valuemax="100" style="width: @Model.UsedPercentage%">
            <span class="sr-only">@Model.UsedPercentage% Used</span>
        </div>
    </div>
</div>

<div class="col-md-6">
    @using (Html.BeginForm("DeleteLogsOlderThanDate", "SuperAdmin", FormMethod.Post, new { date = new DateTime(), id = "PickForm1" }))
    {
        <h3>Sterge toate logurile(Logs) mai vechi de data:</h3>
        <input class="logDatePicker" name="logDate1" value="@DateTime.Today.ToString("dd'/'MM'/'yyyy")" type="text" size="10" style="width: 150px" />
        <label id=" "></label>
        <input class="btn btn-danger" type="submit" value="Sterge" />
    }

    @using (Html.BeginForm("DeleteAuditTrailsOlderThanDate", "SuperAdmin", FormMethod.Post, new { date = new DateTime(), id = "PickForm2" }))
    {
        <h3>Sterge toate auditTrails mai vechi de data:</h3>
        <input class="auditTrailDatePicker" name="logDate2" value="@DateTime.Today.ToString("dd'/'MM'/'yyyy")" type="text" size="10" style="width: 150px" />
        <input class="btn btn-danger" type="submit" value="Sterge" />
    }
</div>

<div class="col-md-6">
    @using (Html.BeginForm("DeletePozeForAnunturiOlderThanDate", "SuperAdmin", FormMethod.Post, new { date = new DateTime(), id = "PickForm2" }))
    {
        <h3>Sterge pozele(secundare - fara prima poza) pentru anunturi inactive mai vechi de data:</h3>
        <input class="pozeDatePicker" name="logDate2" value="@DateTime.Today.AddDays(-200).ToString("dd'/'MM'/'yyyy")" type="text" size="10" style="width: 150px" />
        <input class="btn btn-danger" type="submit" value="Sterge poze" />
    }
</div>

<div class="col-md-12">
    @using (Html.BeginForm("DeleteAnunturiVechiBulk", "SuperAdmin", FormMethod.Post, new { date = new DateTime(), id = "PickForm3" }))
    {
        <h3>Sterge anunturile expirate mai vechi de:</h3>
        <input class="anunturiVechiDatePicker" name="logDate2" value="@DateTime.Today.AddDays(-600).ToString("dd'/'MM'/'yyyy")" type="text" size="10" style="width: 150px" />
        <input class="btn btn-danger" type="submit" value="Sterge anunturi" />
    }
</div>
<br />

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script type="text/javascript">
            //Initialize JQuery UI
            $(function () {
                $(".logDatePicker").datepicker({
                    dateFormat: 'dd/mm/yy',
                    onSelect: function () {
                        //document.getElementById('PickForm1').submit();
                    }
                });

                $(".auditTrailDatePicker").datepicker({
                    dateFormat: 'dd/mm/yy',
                    onSelect: function () {
                        //document.getElementById('PickForm2').submit();
                    }
                });

                $(".anunturiVechiDatePicker").datepicker({
                    dateFormat: 'dd/mm/yy',
                    onSelect: function (date) {
                        $.ajax({
                            type: "GET",
                            url: '@Url.Action("GetNumberDeleteAnunturiVechiBulk", "SuperAdmin")',
                            data: {
                                date: date
                            },
                            contentType: "application/json; charset=utf-8",
                            dataType: "html",
                            success: function (data) {
                                alert(data);
                            },
                            error: function () {
                                alert("Eroare get nr of expired anunturi");
                            }
                        });
                    }
                });

                $(".pozeDatePicker").datepicker({
                    dateFormat: 'dd/mm/yy',
                    onSelect: function (date) {
                        $.ajax({
                            type: "GET",
                            url: '@Url.Action("GetNumberDeletePozeForAnunturiOlderThanDate", "SuperAdmin")',
                            data: {
                                date: date
                            },
                            contentType: "application/json; charset=utf-8",
                            dataType: "html",
                            success: function (data) {
                                alert(data);
                            },
                            error: function () {
                                alert("Eroare get nr of images");
                            }
                        });
                    }
                });
            });
    </script>
}

CoreTestApp/Views/SuperAdmin/MassEmailMessage.cshtml
@model Imobiliare.UI.Models.MassEmailData

@Html.Partial("_MenuSuperAdmin")

@{
    ViewBag.Title = "Send mass email";
    Layout = "_LayoutB4";
}

<h3>Adauga lista de emailuri separate prin virgula. (Doar userii cu cont pe site vor primi email)</h3>

@using (Html.BeginForm("SendMassEmailMessage", "SuperAdmin", FormMethod.Post, new { date = new DateTime(), id = "PickForm" }))
{
    <textarea name="listaEmails" id="listaEmails" style="max-width: 800px; height: 200px; width: 100%"></textarea>
    <br/>
    <button type="button" class="btn btn-success" id="GetAllUsersButton">Adauga toti userii</button>

    <br />
        <br />
        <p style="display: inline-block">Template:</p>
    <select style="max-width: 400px; width: 100%; margin-left: 3px" class="ui-corner-all ui-widget-shadow ui-widget" name="EmailTemplateHumanReadableId">
        @foreach (var emailTemplate in Model.EmailTemplates)
        {
            <option value="@emailTemplate.HumanReadableEmailIdentifier">@emailTemplate.HumanReadableEmailIdentifier</option>
        }
    </select>

    <input type="submit" class="btn btn-success" value="Trimite"/>
}

@section Scripts {
    <script type="text/javascript">
    //Initialize JQuery UI
    $(function () {
        $("#GetAllUsersButton").on("click", function () {
            $.ajax({
                url: '@Url.Action("GetAllUsersFromDBCommaSeparated", "SuperAdmin")',
                type: 'POST',
                data: {
                },
                success: function (data) {
                    //alert(data);
                    $("#listaEmails").html(data);
                }
            });
        });
    });

    </script>
}

CoreTestApp/Views/SuperAdmin/UserEditare.cshtml
@model Imobiliare.Entities.UserProfile
  
<link href="~/Content/bootstrap-toggle.min.css" rel="stylesheet" />

@{
    ViewBag.Title = "UserEditAdmin";
    Layout = "_LayoutB4";
}

<h2>@Model.UserName</h2>
@if (!string.IsNullOrEmpty(Model.Picture))
{
<img src="~/Images/profileImages/@Model.Picture" />
}
<hr />

@using (Html.BeginForm("UpdateUserInfo", "SuperAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

<fieldset>
    <legend>UserProfile @Model.Id</legend>

    @Html.HiddenFor(model => model.Id)

    <div class="editor-label">
        @Html.LabelFor(model => model.UserName)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.UserName)
        @Html.ValidationMessageFor(model => model.UserName)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Role)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Role)
        @Html.ValidationMessageFor(model => model.Role)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.PhoneNumber)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.PhoneNumber)
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>

    @Html.HiddenFor(model => model.TipVanzator)

    <div class="editor-label">
        @Html.LabelFor(model => model.TrustedUser)
    </div>
    <div class="editor-field">
        <input @(Model.TrustedUser ? "checked =\"checked\"" : "") data-toggle="toggle"
               data-on="Da" data-off="Nu" data-size="mini" data-val="true"
               id="TrustedUser" name="TrustedUser" type="checkbox"
               data-width="130" value="true" />
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.Picture)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Picture)
        @Html.ValidationMessageFor(model => model.Picture)
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.AgentieId)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.AgentieId)
        @Html.ValidationMessageFor(model => model.AgentieId)
    </div>


    <div class="editor-label">
        @Html.LabelFor(model => model.Flags)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Flags)
        @Html.ValidationMessageFor(model => model.Flags)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.AbonatLaNewsLetter)
    </div>
    <div class="editor-field">

        <input @(Model.AbonatLaNewsLetter ? "checked =\"checked\"" : "") data-toggle="toggle"
               data-on="Abonat" data-off="Dezabonat" data-size="mini" data-val="true"
               id="AbonatLaNewsLetter" name="AbonatLaNewsLetter" type="checkbox"
               data-width="130" value="true" />
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.RestrictionatPrimireEmail)
    </div>
    <div class="editor-field">

        <input @(Model.RestrictionatPrimireEmail ? "checked =\"checked\"" : "") data-toggle="toggle"
               data-on="Restrictionat" data-off="Nerestrictionat" data-size="mini" data-val="true"
               id="RestrictionatPrimireEmail" name="RestrictionatPrimireEmail" type="checkbox"
               data-width="130" value="true" />
    </div>

    <div class="editor-label">
        @Html.LabelFor(model => model.ReceiveAdminReports)
    </div>
    <div class="editor-field">
        <input @(Model.ReceiveAdminReports ? "checked =\"checked\"" : "") data-toggle="toggle"
               data-on="Da" data-off="Nu" data-size="mini" data-val="true"
               id="ReceiveAdminReports" name="ReceiveAdminReports" type="checkbox"
               data-width="130" value="true" />
    </div>
    <hr />
    <p>
        <input class="btn btn-success" type="submit" value="Salveaza" />
    </p>
</fieldset>
}

@section Scripts {
  <script src="~/Scripts/bootstrap-toggle.min.js"></script>
}