CoreTestApp/Controllers/RaportActivitateController.cs
using System.Globalization;
using Imobiliare.Repositories.Interfaces;
using Imobiliare.UI.Models;
using Imobiliare.UI.Utils.Rapoarte;
using Microsoft.AspNetCore.Mvc;
using Logging;

namespace Imobiliare.UI.Controllers
{
    public class RaportActivitateController : Controller
    {
        private const int DEFAULT_NUMBER_OF_DAYS = 10;
        private string DateFormat = "dd/MM/yyyy";

        private readonly IUnitOfWork unitOfWork;

        private static readonly ILog log = LogManager.GetLogger(typeof(RaportActivitateController));

        public RaportActivitateController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: RaportActivitate
        public async Task<ActionResult> Index(string startDateTime, string endDateTime)
        {
            DateTime startDateTimeFinal = DateTime.Now.AddDays(-DEFAULT_NUMBER_OF_DAYS);
            if (!string.IsNullOrEmpty(startDateTime))
            {
                startDateTimeFinal = DateTime.ParseExact(startDateTime, DateFormat, CultureInfo.InvariantCulture);
            }

            DateTime endDateTimeFinal = DateTime.Now;
            if (!string.IsNullOrEmpty(endDateTime))
            {
                endDateTimeFinal = DateTime.ParseExact(endDateTime, DateFormat, CultureInfo.InvariantCulture);
            }

            var result = new RaportActivitateData
            {
                RaportActivitates = this.unitOfWork.RaportActivitateRepository.Find(x =>
                    x.CreateDateTime >= startDateTimeFinal && x.CreateDateTime <= endDateTimeFinal)
            };
            result.RaportActivitateGraphics =
                RaportActivitateToRaportActivitateGraphicConverter.GenerateRaportActivitateGraphic(
                    result.RaportActivitates);
            result.StartDate = startDateTimeFinal;
            result.EndDate = endDateTimeFinal;
            return View(result);
        }
    }
}

CoreTestApp/Views/RaportActivitate/Delete.cshtml
@model Imobiliare.Entities.RaportActivitate

@{
    ViewBag.Title = "Delete";
    Layout = "_LayoutB4";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RaportActivitate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReceiversCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiversCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StiriAdaugateCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StiriAdaugateCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnsambluriAdaugateCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnsambluriAdaugateCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UseriCreatiCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UseriCreatiCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnunturiByUsersCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnunturiByUsersCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnunturiByAdminCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnunturiByAdminCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SessionStartedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SessionStartedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SessionStartedDistinctCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SessionStartedDistinctCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuditTrailsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuditTrailsCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastConsideredHoursCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastConsideredHoursCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenerareRaportTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenerareRaportTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFakeEmailManager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFakeEmailManager)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CoreTestApp/Views/RaportActivitate/Details.cshtml
@model Imobiliare.Entities.RaportActivitate

@{
    ViewBag.Title = "Details";
    Layout = "_LayoutB4";
}

<h2>Details</h2>

<div>
    <h4>RaportActivitate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReceiversCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiversCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StiriAdaugateCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StiriAdaugateCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnsambluriAdaugateCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnsambluriAdaugateCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UseriCreatiCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UseriCreatiCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnunturiByUsersCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnunturiByUsersCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnunturiByAdminCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnunturiByAdminCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SessionStartedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SessionStartedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SessionStartedDistinctCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SessionStartedDistinctCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuditTrailsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuditTrailsCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastConsideredHoursCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastConsideredHoursCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenerareRaportTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenerareRaportTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFakeEmailManager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFakeEmailManager)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CoreTestApp/Views/RaportActivitate/Index.cshtml
@model Imobiliare.UI.Models.RaportActivitateData
@{
    ViewBag.Title = "Index";
    Layout = "_LayoutB4";
}
<style>
    .sesiuniDistincteTab {
        color: white;
        background-color: darkgoldenrod;
    }

    .anunturiUserTab {
        color: white;
        background-color: darkcyan;
    }

    .anunturiAdminTab {
        color: white;
        background-color: darkred;
    }
</style>

@Html.Partial("_MenuSuperAdmin")
<br />
@using (Html.BeginForm("Index", "RaportActivitate", FormMethod.Get, new { id = "PickForm" }))
{
    <text>De la:</text>
    <input class="datepickerDate" name="startDateTime" value="@Model.StartDate.ToString("dd'/'MM'/'yyyy")" type="text" size="10" style="width: 150px" />
    <text>Pana la:</text>
    <input class="datepickerDate" name="endDateTime" value="@Model.EndDate.ToString("dd'/'MM'/'yyyy")" type="text" size="10" style="width: 150px" />
}
<br />
<h3 style="display: inline-block; color: darkgoldenrod">Sesiuni distincte</h3> |
<h3 style="display: inline-block; color: darkcyan">Anunturi useri</h3> |
<h3 style="display: inline-block; color: darkred">Anunturi admin</h3>
<br />
<div class="row">
    @foreach (var raportGraphic in Model.RaportActivitateGraphics)
    {
        <div>
            <h3><span class="glyphicon glyphicon-time"></span> @raportGraphic.DateTime.ToString("dd-MM-yy")</h3>

            @{
                var sesiuniWidth = raportGraphic.SesiuniDistinctePercentage;
                if (sesiuniWidth < 2)
                {
                    sesiuniWidth = 2;
                }
                var anunturiUserWidth = raportGraphic.AnunturiByUserPercentage;
                if (anunturiUserWidth < 2)
                {
                    anunturiUserWidth = 2;
                }
                var anunturiAdminWidth = raportGraphic.AnunturiByAdminPercentage;
                if (anunturiAdminWidth < 2)
                {
                    anunturiAdminWidth = 2;
                }
            }

            <div class="sesiuniDistincteTab" style="display: inline-block; width: @sesiuniWidth%">
                <div style="float: left; padding-left: 2px">@raportGraphic.SesiuniDistinctePercentage%</div>
                @if (raportGraphic.SessionStartedDistinctCount > 0)
                {
                    <div style="float: right; padding-right: 2px">@raportGraphic.SessionStartedDistinctCount</div>
                }
            </div><br />
            <div class="anunturiUserTab" style="display: inline-block; width: @anunturiUserWidth%">
                <div style="float: left; padding-left: 2px">@raportGraphic.AnunturiByUserPercentage%</div>
                @if (raportGraphic.AnunturiByUsersCount > 0)
                {
                    <div style="float: right; padding-right: 2px">@raportGraphic.AnunturiByUsersCount</div>
                }
            </div><br />
            <div class="anunturiAdminTab" style="display: inline-block; width: @anunturiAdminWidth%">
                <div style="float: left; padding-left: 2px">@raportGraphic.AnunturiByAdminPercentage%</div>
                @if (raportGraphic.AnunturiByAdminCount > 0)
                {
                    <div style="float: right; padding-right: 2px">@raportGraphic.AnunturiByAdminCount</div>
                }
            </div>
        </div>

    }
</div>

<h3 style="color: red">Rapoartele acestea sunt generate periodic la 48h, si sunt salvate in Baza de date. Coincide cu informatiile ce sunt trimise pe mail la admin.</h3>

<table class="table">
    <tr>
        <th>
            StiriAdaugate
        </th>
        <th>
            AnsambluriAdaugate
        </th>
        <th>
            UseriCreati
        </th>
        <th>
            AnunturiByUsers
        </th>
        <th>
            AnunturiByAdmin
        </th>
        <th>
            SessionStarted
        </th>
        <th>
            Sesiuni Distincte
        </th>
        <th>
            AuditTrails
        </th>
        <th>
            LastConsideredHours
        </th>
        <th>
            CreateDateTime
        </th>
        <th>
            GenerareRaportTime
        </th>
        <th>
            IsFakeEmailManager
        </th>
    </tr>

    @foreach (var item in Model.RaportActivitates)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StiriAdaugateCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnsambluriAdaugateCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UseriCreatiCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnunturiByUsersCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnunturiByAdminCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SessionStartedCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SessionStartedDistinctCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuditTrailsCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastConsideredHoursCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GenerareRaportTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsFakeEmailManager)
            </td>
        </tr>
    }

</table>


@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script type="text/javascript">
        $(function () {
            $(".datepickerDate").datepicker({
                dateFormat: 'dd/mm/yy',
                onSelect: function () {
                    document.getElementById('PickForm').submit();
                }
            });
        });
    </script>
}