CoreTestApp/Models/Stiri/StireViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Imobiliare.Entities;

namespace Imobiliare.UI.Models
{
  public class StireViewModel
  {
    public Stire Stire { get; set; }

    public Stire StireAnterioara { get; set; }

    public Stire StireUrmatoare { get; set; }

    public List<Imobil> LastAddedImobils { get; set; }
  }
}

CoreTestApp/Models/Stiri/StiriViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Imobiliare.Entities;

namespace Imobiliare.UI.Models
{
    public class StiriViewModel
    {
        public List<Stire> Stiri { get; set; }

        public int NumberOfPages { get; set; }

        public StiriFilter StiriFilter { get; set; }

        //For generic paging, which needs the property on the Model directly
        public int Page => StiriFilter.Page;
    }
}

CoreTestApp/Controllers/StiriController.cs
using Imobiliare.Entities;
using Imobiliare.Repositories.Interfaces;
using Imobiliare.UI.Models;
using Imobiliare.UI.Utils.UrlSeoFormatters;
using Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Imobiliare.UI.Controllers
{
    public class StiriController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        private static readonly ILog log = LogManager.GetLogger(typeof(StiriController));

        public StiriController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: Stiri
        public ActionResult Index(int? page)
        {
            var selectedPageFinal = 1;

            if (page != null)
            {
                selectedPageFinal = page.Value;
            }

            var stiriViewModel = CreateStiriViewModel(selectedPageFinal, true);
            return View(stiriViewModel);
        }

        private StiriViewModel CreateStiriViewModel(int selectedPageFinal, bool? onlyActive)
        {
            StiriFilter stiriFilter = new StiriFilter();
            stiriFilter.Active = onlyActive;
            stiriFilter.Page = selectedPageFinal;
            StiriViewModel stiriViewModel = new StiriViewModel();
            int totalNumberOfStiri;
            stiriViewModel.Stiri = this.unitOfWork.StiriRepository.GetFiltered(
                x => stiriFilter.Active == null || stiriFilter.Active != null && x.Active == stiriFilter.Active.Value,
                stiriFilter, out totalNumberOfStiri);
            stiriViewModel.StiriFilter = stiriFilter;
            var displayPageNumber = (int)Math.Ceiling((double)totalNumberOfStiri / stiriFilter.PageSize);
            stiriViewModel.NumberOfPages = displayPageNumber;
            return stiriViewModel;
        }

        [Authorize(Roles = "Admin")]
        // GET: Stiri
        public ActionResult IndexAdmin(int? page)
        {
            var selectedPageFinal = 1;

            if (page != null)
            {
                selectedPageFinal = page.Value;
            }

            var stiriViewModel = CreateStiriViewModel(selectedPageFinal, null);
            return View(stiriViewModel);
        }

        [Authorize(Roles = "Admin")]
        // GET: Stiri/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return StatusCode((int)HttpStatusCode.BadRequest);
            }

            //Use cached single overriden version
            Stire stire = this.unitOfWork.StiriRepository.Single(x => x.Id == id.Value);
            if (stire == null)
            {
                return StatusCode((int)HttpStatusCode.NotFound);
            }
            return View(stire);
        }

        [Authorize(Roles = "Admin")]
        // GET: Stiri/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stiri/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
          [Bind("StireId,CategorieStire,Titlu,TitluUrl,Continut,DateCreated,DateModified,NumarVizualizari,Poze,Active,AfiseazaPrimaPagina,Keywords,OrasSelect,MetaDescription"
        )] Stire stire)
        {
            if (ModelState.IsValid)
            {
                stire.UserProfile = this.unitOfWork.UsersRepository.Single(x => x.Email == User.Identity.Name);
                stire.DateCreated = DateTime.Now;
                stire.DateModified = DateTime.Now;
                this.unitOfWork.StiriRepository.Add(stire);
                this.unitOfWork.AuditTrailRepository.AddAuditTrail(AuditTrailCategory.Message, $"Created stire: {stire.Titlu}", userName: User.Identity.Name, notifyAdmin: true);
                this.unitOfWork.Complete();
                TempData["FooterStatus"] = "Stire creata cu succes";
                return RedirectToAction("Edit", new { id = stire.Id });
            }

            TempData["ErrorMessage"] = "Eroare la crearea stiri, va rugam completati toate campurile";
            return View(stire);
        }

        [Authorize(Roles = "Admin")]
        // GET: Stiri/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return StatusCode((int)HttpStatusCode.BadRequest);
            }
            Stire stire = this.unitOfWork.StiriRepository.Single(x => x.Id == id.Value);
            if (stire == null)
            {
                return StatusCode((int)HttpStatusCode.NotFound);
            }
            if (stire.OrasSelect != 0)
            {
                ViewBag.OrasSelectat = this.unitOfWork.OrasRepository.Single(x => x.Id == stire.OrasSelect);
            }
            return View(stire);
        }

        [Authorize(Roles = "Admin")]
        // POST: Stiri/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
          [Bind("Id,CategorieStire,Titlu,TitluUrl,Continut,DateCreated,DateModified,NumarVizualizari,Poze,Active,AfiseazaPrimaPagina,Keywords,OrasSelect,MetaDescription"
        )] Stire stire)
        {
            if (ModelState.IsValid)
            {
                this.unitOfWork.StiriRepository.Edit(stire);
                this.unitOfWork.Complete();
                log.Debug($"Edited stire: {stire.Titlu}");
                TempData["FooterStatus"] = "Stire editata cu succes";
                TempData["Message"] = "Stire editata cu succes";
                return RedirectToAction("Edit", new { id = stire.Id });
            }
            return View(stire);
        }

        [Authorize(Roles = "Admin")]
        // GET: Stiri/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return StatusCode((int)HttpStatusCode.BadRequest);
            }
            Stire stire = this.unitOfWork.StiriRepository.Single(x => x.Id == id.Value);
            if (stire == null)
            {
                return StatusCode((int)HttpStatusCode.NotFound);
            }
            return View(stire);
        }

        [Authorize(Roles = "Admin")]
        // POST: Stiri/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            this.unitOfWork.StiriRepository.Delete(id);
            this.unitOfWork.Complete();
            log.Debug($"Deleted stire with id: {id.ToString()}");
            TempData["FooterStatus"] = "Stire stearsa cu succes";
            return RedirectToAction("Index");
        }

        [Route("Stire/{titlu}/{stireId}")]
        public ActionResult Stire(string titlu, string stireId)
        {
            int id;
            int.TryParse(stireId, out id);
            if (id == 0)
            {
                return StatusCode((int)HttpStatusCode.BadRequest);
            }

            var stire = this.unitOfWork.StiriRepository.TryGetCachedStire(id);

            //Check if title changed in the meantime, do 301 redirect in case
            //Same in HomeController - ApartamentDetalii
            var url = StiriUrls.BuildStirePageUrl(stire);

            var newTitle = url.Split('/')[2];

            if (!string.IsNullOrEmpty(titlu) && titlu != newTitle)
            {
                log.Warn($"STIRE Redirect permanent because of stire title change for stire {stire.Id} with original title {titlu} and updated title {newTitle}");
                return RedirectPermanent(url);
            }

            //Log
            var name = string.Empty;
            if (User.Identity.Name != string.Empty)
            {
                name = User.Identity.Name;
            }
            //if (!Request.Iscrawler())
            //{
            //    log.Debug($"User: {0}, ip: {1} accessed stire with id {2}, titlu {3}", name != string.Empty ? name : "unknown user",
            //      Request.UserHostAddress, stire.Id, titlu);
            //}

            var stireViewModel = new StireViewModel();
            stireViewModel.Stire = stire;

            if (stire.OrasSelect != 0)
            {
                var imobilFilter = new ImobilFilter
                {
                    PageSize = 4,
                    OrasId = stire.OrasSelect,
                    StareAprobare = StareAprobare.Aprobat
                };
                int totalNumberOfPages;
                var anunturi = this.unitOfWork.AnunturiRepository.GetAllImobil(imobilFilter, out totalNumberOfPages);
                if (anunturi.Count != 0)
                {
                    stireViewModel.LastAddedImobils = anunturi;
                }
                else
                {
                    stireViewModel.LastAddedImobils = this.unitOfWork.AnunturiRepository.GetLastAddedImobils(4);
                }
            }
            else
            {
                stireViewModel.LastAddedImobils = this.unitOfWork.AnunturiRepository.GetLastAddedImobils(4);
            }
            StiriFilter stiriFilter = new StiriFilter();
            stiriFilter.Active = true;
            Tuple<Stire, Stire> stiriNavigation = this.unitOfWork.StiriRepository.FindBeforeAndAfterNavigationStiri(id, stiriFilter);

            stireViewModel.StireAnterioara = stiriNavigation.Item1;
            stireViewModel.StireUrmatoare = stiriNavigation.Item2;

            return this.View("Stire", stireViewModel);
        }

        //[HttpPost]
        //public ActionResult AddImageNoAjax(HttpPostedFileBase file)
        //{

CoreTestApp/Views/Stiri/Edit.cshtml
@using Imobiliare.Entities
@model Imobiliare.Entities.Stire

@Html.Partial("_MenuSuperAdmin")

@{
  ViewBag.Title = "Edit";
    Layout = "_LayoutB4";
}

<h2>Editeaza stire</h2>

<style>
  input[type="text"], input[type="password"], textarea {
    max-width: 100%;
  }
</style>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>Stire</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
      @Html.LabelFor(model => model.CategorieStire, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.CategorieStire, Enum.GetNames(typeof(CategorieStire)).Select(e => new SelectListItem { Text = e }))
        @*@Html.EnumDropDownListFor(model => model.EmailTemplateCategory, htmlAttributes: new { @class = "form-control" })*@
        @Html.ValidationMessageFor(model => model.CategorieStire, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Titlu, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Titlu, new { style = "width: 100%; max-width:100%", htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Titlu, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-md-2"></label>
      <label class="control-label col-md-10" style="text-align: left">www.apartament24.ro/Stire/Titlu-Url/1 (Lasa gol pentru formare url din Titlul stirii)</label>
      <label class="control-label col-md-2">Titlu Url(Foloseste '-' in loc de spatii)</label>
      <div class="col-md-8">
        @Html.EditorFor(model => model.TitluUrl, new { style = "width: 100%; max-width:100%", htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TitluUrl, "", new { @class = "text-danger" })
      </div>
    </div>
    
    <div class="form-group">
      <label class="control-label col-md-2"></label>
      <label class="control-label col-md-10" style="text-align: left">Apare la meta + la facebook share la descriere (Lasa gol pentru formare meta din Titlul stirii)</label>
      <label class="control-label col-md-2">Meta Description</label>
      <div class="col-md-8">
        @Html.EditorFor(model => model.MetaDescription, new { style = "width: 100%; max-width:100%", htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Continut, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.TextAreaFor(model => model.Continut, new { style = "width: 100%; height: 400px; max-width:100%", htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Continut, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        <div class="checkbox">
          @Html.EditorFor(model => model.Active)
          @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
        </div>
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.AfiseazaPrimaPagina, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        <div class="checkbox">
          @Html.EditorFor(model => model.AfiseazaPrimaPagina)
          @Html.ValidationMessageFor(model => model.AfiseazaPrimaPagina, "", new { @class = "text-danger" })
        </div>
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
      </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.OrasSelect, htmlAttributes: new { @class = "control-label col-md-2" })

        <div style="position: relative; display: inline-block">
          <input type="text" autocomplete="off" style="color: #c3c3c3; font-size: 1.3em; margin-left: 5px" class="searchBox" value="@(ViewBag.OrasSelectat != null ? ((Oras)ViewBag.OrasSelectat).Nume : "Introduceti Localitate")" onfocus="inputFocus(this)" onblur="inputBlur(this)" name="searchBox" />
          <ul class="localitatiSearchResult"></ul>
        </div>
        <div style="display: inline-block">
          <input class="form-control text-box single-line" id="OrasSelect" name="OrasSelect" type="hidden" value="@Model.OrasSelect">
        </div>
      </div>*@

    <div class="form-group">
      @Html.LabelFor(model => model.OrasSelect, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        <div style="display: inline-block; position: relative; width: 100%">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            @Html.Label("", "Localitate")

            <input type="text" autocomplete="off" style="max-width: 600px; width: 100%" class="searchBox form-control" value="@(ViewBag.OrasSelectat != null ? ((Oras)ViewBag.OrasSelectat).Nume : "")" placeholder="Introduceti Localitate" name="searchBox" @(ViewBag.OrasSelectat != null ? "disabled" : "") />
            <input type="hidden" name="OrasSelect" id="OrasSelect" value="@Model.OrasSelect" />
            <ul style="max-height: 450px; overflow-y: scroll" class="localitatiSearchResult"></ul>
          </div>

          <div class="schimbaLocalitateButton" style="@(ViewBag.OrasSelectat == null ? "display:none;":"") position: absolute; right: 5px; top: 20px; z-index: 30">
            <button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-remove"></span> Schimba</button>
          </div>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Salveaza" class="btn btn-success" />
      </div>
    </div>
  </div>
}

<h3 style="color:red">Adaugarea unei poze va face refresh la pagina. Salvati stirea daca aveti modificari, inainte de a adauga poze!</h3>

<div class="row" style="border-top: 1px solid #a7d582; background-color: #F9F9F9; border-radius: 4px; margin-bottom: 20px">
  <div class="col-md-6">
    <div class="col-md-5">
      <h3 id="AddPhotoMessage">Selectează Poza <span class="glyphicon glyphicon glyphicon-camera"></span></h3>
      @*@if(string.IsNullOrEmpty(Model.Poze))
        {*@
      <div>
        @using (Html.BeginForm("AddImageNoAjax", "Stiri", FormMethod.Post, new { enctype = "multipart/form-data", id = "NoFlashUploadForm" }))
        {
          <input type="hidden" name="stireId" value="@Model.Id" />
                        <input type="file" name="file" id="file" />
                        <div style="padding: 5px">
                          <input type="submit" class="btn btn-success" value="Încarcă Poză">
                        </div>
        }
      </div>
      @*}*@
    </div>

  </div>
  <div class="col-md-6">

    @if (!string.IsNullOrEmpty(Model.Poze))
    {
      foreach (var poza in Model.Poze.Split(';'))
      {
        <div>
          <div style="display: inline-block; width: 200px">
            <img style="max-width: 200px; max-height: 120px" src="/Images/Stiri/@poza" />
          </div>
          <div style="display: inline-block">

            <input type="button" class="btn btn-success insertImgButton" value="Insereaza">
            @using (Html.BeginForm("StergeImagine", "Stiri", FormMethod.Post))
            {
                <input type="hidden" name="stireId" value="@Model.Id" />
                <input type="hidden" name="poza" value="@poza" />
                  <div style="padding-top: 5px">
                    <input type="submit" class="btn btn-danger" value="Sterge Poză">
                  </div>
            }
          </div>
        </div>
      }
    }
  </div>
</div>

<div>
  @Html.ActionLink("Înapoi la stiri", "IndexAdmin", null, new { @class = "btn btn-success" })
</div>

@section Scripts {
  @Html.Partial("_SearchBoxOrasFindWithRemoveScript")
  <script>
    $(document).ready(function () {
      $(".insertImgButton").on("click", function () {
        //alert($(this).closest('div').prev().find('img').attr('src'));
        var imgSrc = $(this).closest('div').prev().find('img').attr('src');
        var link = "<div class=\"col-xs-12 col-md-12 col-lg-8\" style=\"padding:0\"><img style=\"width:100%; padding:0\" src=\"" + imgSrc + "\"></div><div class=\"clearfix\"></div>";
        insertAtCaret("Continut", link);
      });
    });

    function insertAtCaret(areaId, text) {
      var txtarea = document.getElementById(areaId);
      var scrollPos = txtarea.scrollTop;
      var strPos = 0;
      var br = ((txtarea.selectionStart || txtarea.selectionStart == '0') ?
        "ff" : (document.selection ? "ie" : false));
      if (br == "ie") {
        txtarea.focus();
        var range = document.selection.createRange();
        range.moveStart('character', -txtarea.value.length);
        strPos = range.text.length;
      }
      else if (br == "ff") strPos = txtarea.selectionStart;

      var front = (txtarea.value).substring(0, strPos);
      var back = (txtarea.value).substring(strPos, txtarea.value.length);
      txtarea.value = front + text + back;
      strPos = strPos + text.length;
      if (br == "ie") {
        txtarea.focus();
        var range = document.selection.createRange();
        range.moveStart('character', -txtarea.value.length);
        range.moveStart('character', strPos);
        range.moveEnd('character', 0);
        range.select();
      }
      else if (br == "ff") {
        txtarea.selectionStart = strPos;
        txtarea.selectionEnd = strPos;
        txtarea.focus();
      }
      txtarea.scrollTop = scrollPos;
    }

  </script>
}

CoreTestApp/Views/Stiri/Index.cshtml
@using System.Text.RegularExpressions
@using Imobiliare.UI.Utils.UrlSeoFormatters
@model Imobiliare.UI.Models.StiriViewModel

@{
    ViewBag.Title = "Stiri imobiliare";

    ViewBag.MetaDescription = "Noutati din sectorul imobiliar, stiri despre evolutia pietei imobiliare din Romania.";
    Layout = "_LayoutB5";
}

<title>Știri</title>

<div class="container">
    <h2>Știri</h2>
    <hr />

    @foreach (var stire in Model.Stiri)
    {

        <a class="linkDiv" href="@StiriUrls.BuildStirePageUrl(stire)">
            <div style="border: 1px solid #a7d582; border-radius: 4px; box-shadow: 3px 3px 2px #888888; margin-bottom: 7px; padding: 5px">
                <h2>@Html.DisplayFor(modelItem => stire.Titlu)</h2>
                <hr />

                @if (!string.IsNullOrEmpty(stire.Poze))
                {
                    @*Remove this for example with this line: <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>*@
                    stire.Continut = Regex.Replace(stire.Continut, "<script.*?>(.|\n)*?</script>", string.Empty);
                    var continut = Regex.Replace(stire.Continut, "<.*?>", String.Empty);
                    <div class="row d-flex align-items-center">
                        <div class="col-md-4">
                            <img style="width: 100%" src="/Images/Stiri/@stire.Poze.Split(';')[0]" alt="@stire.Titlu"/>
                        </div>
                        <div class="col-md-8" style="font-size: 1.2em">
                            @if (continut.Length < 200)
                            {
                                @continut
                            }
                            else
                            {
                                @Html.Raw(continut.Substring(0, 200))
                                @:...
                            }
                        </div>
                    </div>
                    <div class="clearfix"></div>
                }
                else
                {
                    @*Remove this for example with this line: <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>*@
                    stire.Continut = Regex.Replace(stire.Continut, "<script.*?>(.|\n)*?</script>", string.Empty);
                    var continut = Regex.Replace(stire.Continut, "<.*?>", String.Empty);
                    <div class="row">
                        @if (continut.Length < 200)
                        {
                            @continut
                        }
                        else
                        {
                            @Html.Raw(continut.Substring(0, 200))
                            @:...
                        }
                    </div>
                }
                <p><span class="bi bi-calendar"></span> @stire.DateCreated.Date.ToString("dd/MM/yy")</p>
                <p>
                    @Html.DisplayFor(modelItem => stire.CategorieStire)
                </p>
            </div>
        </a>
    }

    @if (Model.NumberOfPages > 1)
    {
        <p style="margin: 10px 0 0 0">Pagina @Model.StiriFilter.Page din @Model.NumberOfPages</p>
        <nav>
            <ul class="pagination pagination-lg"></ul>
        </nav>
    }

    @using (Html.BeginForm("Index", "Stiri", FormMethod.Get, new { date = new DateTime(), id = "PickForm" }))
    {
        //For paging to insert page element
    }
</div>

@section nextprev {
    @Html.Partial("_GenericNextPrev")
}

@section Scripts {
    @Html.Partial("_GenericPagingB5")
}

CoreTestApp/Views/Stiri/IndexAdmin.cshtml
@using System.Text.RegularExpressions
@using Imobiliare.UI.Utils.UrlSeoFormatters
@model Imobiliare.UI.Models.StiriViewModel

@Html.Partial("_MenuSuperAdmin")

@{
    ViewBag.Title = "Index";
    Layout = "_LayoutB4";
}

@Html.ActionLink("Adauga Stire", "Create", null, new { style = "margin-top: 10px", @class = "btn btn-success" })

<table class="table table-hover table-striped">
    <tr>
        <th>
            Imagine
        </th>
        <th>
            Categorie
        </th>
        <th>
            Titlu
        </th>
        <th>
            DateCreated
        </th>
        <th>
            DateModified
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.NumarVizualizari)
            </th>*@
        <th>
            Poze
        </th>
        <th>
            Active
        </th>
        @*<th>
                AfisarePrimaPag
            </th>*@
        <th>
            Keywords
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Stiri)
    {
        <tr>
            <td>
                @if (!(string.IsNullOrEmpty(item.Poze)))
                {
                    <a href="@StiriUrls.BuildStirePageUrl(item)"><img style="max-height: 50px; max-width: 100px" src="~/Images/Stiri/@item.Poze.Split(';').First()" /></a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategorieStire)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titlu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateModified)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.NumarVizualizari)
                </td>*@
            <td>
                @(!string.IsNullOrEmpty(item.Poze) ? item.Poze.Split(';').Count().ToString() : "0")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.AfiseazaPrimaPagina)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Keywords)
            </td>
            <td>
                @Html.ActionLink("Editeaza", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalii", "Details", new { id = item.Id }) |
                @Html.ActionLink("Sterge", "Delete", new { id = item.Id }, new { @style = "color:red" })
            </td>
        </tr>
    }

</table>

@if (Model.NumberOfPages > 1)
{
    <p style="margin: 10px 0 0 0">Pagina @Model.StiriFilter.Page din @Model.NumberOfPages</p>
    <nav>
        <ul class="pagination pagination-lg"></ul>
    </nav>
}

@using (Html.BeginForm("IndexAdmin", "Stiri", FormMethod.Get, new { date = new DateTime(), id = "PickForm" }))
{

}

@section Scripts {
    @Html.Partial("_GenericPaging")
}